name: Maven Publishing

on:
  push:
    branches:
        - 'develop'
  pull_request:
    branches:
        - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN

    - name: Build and Publish with Maven
      run: mvn -B clean deploy --file pom.xml
      env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}